### ISSUE TITLE
Add a License file

### ISSUE THREAD

**Issue by LesleyLai** [cdgiessen/CERT#1]
Someone wants to use some code from this project, but is stopped since the project doesn't contain a license file.

**Comment by charles-lunarg** [comment]
Ah whoops. What license do you suggest? I often go for MIT, but Apache 2 is also fine with me.

**Comment by LesleyLai** [comment]
MIT?

**Comment by charles-lunarg** [comment]
Aaaand done!

**Comment by cdgiessen** [comment]
UGH I used the wrong account 🤦 
Thanks for letting me know about the issue :)
